import { useCallback, useEffect, useMemo, useReducer, useState, type DragEvent } from 'react';
import { Background, Controls, MiniMap, ReactFlow, ReactFlowProvider, Handle, Position, useReactFlow, type Connection, type NodeProps } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Link } from 'react-router-dom';
import Navbar from '../../components/Navbar';
import SeoHead from '../../seo/SeoHead';
import { analyzeArchitecture, calculateChangeImpact, calculateMetrics, listChangeImpact, validateTicket } from './engine';
import { componentCatalog, difficultyOptions, modules, tickets } from './data';
import { gameReducer, loadGame, saveGame } from './state';
import type { ComponentNodeData, GameEdge, GameNode, GameState, ModuleNodeData } from './types';
import './monolith.css';

function ModuleNode({ id, data }: NodeProps<GameNode>) {
  const module = data as ModuleNodeData & { onToggle?: (id: string) => void };
  return <div className={`module-node ${module.collapsed ? 'collapsed' : ''}`} style={{ borderColor: module.color }}><div className="module-heading"><span className="module-orb" style={{ background: module.color }} /><strong>{module.name}</strong><button type="button" aria-label={`${module.collapsed ? 'Expandir' : 'Contraer'} ${module.name}`} onClick={(event) => { event.stopPropagation(); module.onToggle?.(id); }}>{module.collapsed ? '+' : '−'}</button></div>{!module.collapsed && <><small>{module.description}</small><span className="module-boundary-label">MÓDULO INTERNO</span></>}</div>;
}
function ComponentNode({ data, selected }: NodeProps<GameNode>) {
  const component = data as ComponentNodeData;
  return <div className={`component-node ${selected ? 'selected' : ''}`}><Handle type="target" position={Position.Left} /><span>{component.kind}</span><strong>{component.name}</strong><Handle type="source" position={Position.Right} /></div>;
}
const nodeTypes = { group: ModuleNode, component: ComponentNode };
function MonolithCanvas({ state, dispatch, onSelect }: { state: GameState; dispatch: React.Dispatch<Parameters<typeof gameReducer>[1]>; onSelect: (id: string | null) => void }) {
  const flow = useReactFlow<GameNode, GameEdge>();
  const nodes = useMemo(() => state.nodes.map((node) => {
    if (node.type === 'group') return { ...node, style: { ...node.style, height: node.data.collapsed ? 82 : 190 }, data: { ...node.data, onToggle: (id: string) => dispatch({ type: 'toggle-module', moduleId: id }) } };
    const parent = state.nodes.find((entry) => entry.id === node.parentId);
    return { ...node, hidden: Boolean(parent?.data.collapsed) };
  }), [state.nodes, dispatch]);
  const onConnect = useCallback((connection: Connection) => {
    const source = state.nodes.find((node) => node.id === connection.source);
    const target = state.nodes.find((node) => node.id === connection.target);
    if (!source || !target || source.type === 'group' || target.type === 'group' || source.id === target.id) return;
    const reason = window.prompt(`¿Por qué ${source.data.name} necesita ${target.data.name}?`, 'Necesita su capacidad para cumplir el requerimiento');
    if (reason === null) return;
    dispatch({ type: 'add-edge', edge: { ...connection, id: `${connection.source}-${connection.target}`, source: connection.source!, target: connection.target!, type: 'smoothstep', animated: true, data: { reason, couplingWeight: state.difficulty === 'hard' ? 3 : state.difficulty === 'medium' ? 2 : 1 }, label: 'usa' } });
  }, [dispatch, state.difficulty, state.nodes]);
  const onDrop = (event: DragEvent) => {
    event.preventDefault(); const definitionId = event.dataTransfer.getData('application/monolith-component'); if (!definitionId) return;
    const definition = componentCatalog.find((item) => item.id === definitionId); if (!definition) return;
    const position = flow.screenToFlowPosition({ x: event.clientX, y: event.clientY });
    const moduleNodes = state.nodes.filter((node) => node.type === 'group');
    const owner = moduleNodes.find((node) => position.x >= node.position.x && position.x <= node.position.x + 260 && position.y >= node.position.y && position.y <= node.position.y + 190) ?? moduleNodes[0];
    if (owner) dispatch({ type: 'add-component', moduleId: owner.id, definitionId, name: definition.name, kind: definition.kind, description: definition.description });
  };
  return <div className="monolith-canvas" onDrop={onDrop} onDragOver={(event) => event.preventDefault()}><div className="monolith-label"><strong>MONOLITH</strong><span>UNA APLICACIÓN · UN DEPLOYMENT</span></div><ReactFlow nodes={nodes} edges={state.edges} nodeTypes={nodeTypes} onNodesChange={(changes) => dispatch({ type: 'nodes', changes })} onEdgesChange={(changes) => dispatch({ type: 'edges', changes })} onConnect={onConnect} onNodeClick={(_, node) => onSelect(node.type === 'group' ? null : node.id)} onPaneClick={() => onSelect(null)} onNodeDragStop={(_, node) => { if (node.type === 'group') return; const absolute = flow.getInternalNode(node.id)?.internals.positionAbsolute ?? node.position; const owner = state.nodes.filter((entry) => entry.type === 'group').find((entry) => absolute.x >= entry.position.x && absolute.x <= entry.position.x + 260 && absolute.y >= entry.position.y && absolute.y <= entry.position.y + 190); if (owner && owner.id !== node.parentId) dispatch({ type: 'move-component', componentId: node.id, moduleId: owner.id, position: { x: absolute.x - owner.position.x, y: absolute.y - owner.position.y }, moduleName: String(owner.data.name) }); }} fitView minZoom={0.35} maxZoom={1.5} proOptions={{ hideAttribution: true }}><Background color="#ffffff18" gap={22} /><Controls /><MiniMap nodeColor={(node) => String((node.data as ModuleNodeData).color ?? '#9388ff')} maskColor="#080810aa" /></ReactFlow></div>;
}

function MonolithGameContent() {
  const [state, dispatch] = useReducer(gameReducer, undefined, loadGame);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [toast, setToast] = useState('');
  const [filter, setFilter] = useState('');
  useEffect(() => { saveGame(state); }, [state]);
  const metrics = useMemo(() => calculateMetrics(state.nodes, state.edges), [state.nodes, state.edges]);
  const warnings = useMemo(() => analyzeArchitecture(state.nodes, state.edges), [state.nodes, state.edges]);
  const ticket = tickets[Math.min(state.activeTicketIndex, tickets.length - 1)];
  const selected = state.nodes.find((node) => node.id === selectedId && node.type !== 'group');
  const completion = (state.completedTickets.length / tickets.length) * 100;
  const addComponent = (id: string, moduleId: string) => { const definition = componentCatalog.find((item) => item.id === id); const targetModule = modules.find((item) => item.id === moduleId); if (definition && targetModule) dispatch({ type: 'add-component', moduleId, definitionId: id, name: definition.name, kind: definition.kind, description: definition.description }); };
  const addTicketComponent = (id: string) => { const definition = componentCatalog.find((item) => item.id === id); if (definition) addComponent(id, definition.moduleId); };
  const validate = () => {
    const result = validateTicket(ticket, state.nodes, state.edges);
    if (!result.valid) { const missing = [...result.missingComponents.map((id) => componentCatalog.find((item) => item.id === id)?.name ?? id), ...result.missingDependencies.map(([source, target]) => `${componentCatalog.find((item) => item.id === source)?.name} → ${componentCatalog.find((item) => item.id === target)?.name}`)]; setToast(`Faltan: ${missing.join(', ')}`); return; }
    dispatch({ type: 'complete-ticket', ticketId: ticket.id }); setToast(`✓ Requerimiento completado. ${ticket.explanation}`);
  };
  const metricLabel = (value: number) => value < 30 ? 'BAJO' : value < 60 ? 'MEDIO' : 'ALTO';
  const impact = selected ? calculateChangeImpact(selected.parentId ?? selected.id, state.nodes, state.edges) : 0;
  const handleReset = () => { if (window.confirm('¿Reiniciar la partida y borrar el progreso guardado?')) dispatch({ type: 'reset' }); };
  const handleGod = () => {
    dispatch({ type: 'god-module' });
    const shortcuts = [
      ['common-god-service', 'CommonService'], ['common-order-logic', 'OrderLogic'], ['common-product-logic', 'ProductLogic'],
      ['common-payment-logic', 'PaymentLogic'], ['common-report-logic', 'ReportLogic'], ['common-user-logic', 'UserLogic'],
    ] as const;
    shortcuts.forEach(([id, name]) => dispatch({ type: 'add-component', moduleId: 'common', definitionId: id, name, kind: 'service', description: 'Responsabilidad de dominio concentrada en Common para ahorrar tiempo.' }));
    state.nodes.filter((node) => node.type === 'component' && node.data.kind === 'service').forEach((node) => dispatch({ type: 'add-edge', edge: { id: `${node.id}-common-god-service`, source: node.id, target: 'common-god-service', type: 'smoothstep', animated: true, data: { reason: 'Atajo temporal: concentrar la lógica en CommonService', couplingWeight: 2 } } }));
    setToast('CommonService concentra responsabilidades: varios módulos dependen del mismo punto y los cambios se propagan.');
  };
  const handleChangeEvent = () => { const affected = listChangeImpact('payments', state.nodes, state.edges).map((id) => String(state.nodes.find((node) => node.id === id)?.data.name ?? id)); setToast(`Cambio de proveedor de pagos: ${affected.length} componentes podrían necesitar cambios: ${affected.join(', ') || 'todavía ninguno; agregá Payments y sus dependencias'}.`); dispatch({ type: 'change-event' }); };
  const onPaletteDrag = (event: DragEvent, id: string) => { event.dataTransfer.setData('application/monolith-component', id); event.dataTransfer.effectAllowed = 'copy'; };
  return <><SeoHead page="monolithMayhem" /><Navbar user={null} onOpenLogin={() => undefined} showAuthControls={false} /><main className="games-page monolith-page"><header className="defender-heading monolith-heading"><Link className="games-back-link" to="/games">← Todos los juegos</Link><p className="games-eyebrow">JUEGO 02 · ARQUITECTURA</p><h1>Monolith Mayhem</h1><p>Construí un monolito. Mantenelo sano. Sobreviví a los cambios.</p></header>
    {!state.tutorialComplete && <section className="tutorial-card"><div><span className="tutorial-step">ANTES DE EMPEZAR · 3 IDEAS</span><h2>Un monolito también puede tener límites claros</h2><ol><li>Un monolito es una única aplicación desplegable.</li><li>Puede contener varios módulos internos separados.</li><li>El desafío es decidir cómo se conocen esos módulos.</li></ol><button className="game-primary-button" onClick={() => dispatch({ type: 'tutorial' })}>Empezar a construir</button></div></section>}
    <section className="monolith-shell"><header className="monolith-hud"><div className="hud-title"><span className="monolith-mark">⬡</span><div><strong>MONOLITH MAYHEM</strong><small>NIVEL {state.currentLevel} · {state.currentLevel > 1 ? 'MODULAR MONOLITH' : 'BASIC MONOLITH'}</small></div></div><div className="hud-score"><span>SCORE</span><strong>{state.score + metrics.score}</strong></div><div className="health-meter"><span>ARCHITECTURE HEALTH</span><strong>{metrics.architectureHealth}%</strong><div><i style={{ width: `${metrics.architectureHealth}%` }} /></div></div><button className="game-small-button" onClick={handleReset}>↻ Reiniciar</button></header>
      <div className="metric-strip">{[['Coupling', metrics.coupling], ['Complexity', metrics.complexity], ['Change Risk', Math.min(100, metrics.changeImpact * 8 + warnings.filter((warning) => warning.severity === 'danger').length * 25)]].map(([name, value]) => <div className="metric-chip" key={name}><span>{name}</span><strong>{metricLabel(Number(value))}</strong><small>{value}/100</small></div>)}<div className="metric-chip cohesion-chip"><span>Cohesion</span><strong>{metrics.cohesion}%</strong></div></div>
      <div className="game-workspace"><aside className="game-side-panel component-palette"><header><span>01 · TOOLBOX</span><h2>Componentes</h2><p>Arrastrá una pieza hasta un módulo del canvas.</p></header><input aria-label="Filtrar componentes" placeholder="Buscar componente…" value={filter} onChange={(event) => setFilter(event.target.value)} />{modules.filter((module) => module.id !== 'common' || state.currentLevel > 1).map((module) => <div className="palette-group" key={module.id}><h3><i style={{ background: module.color }} />{module.name}</h3>{componentCatalog.filter((component) => component.moduleId === module.id && component.name.toLowerCase().includes(filter.toLowerCase())).map((component) => <button type="button" draggable onDragStart={(event) => onPaletteDrag(event, component.id)} onClick={() => addComponent(component.id, module.id)} key={component.id} className="palette-item"><span>{component.kind}</span><strong>{component.name}</strong><b>+</b></button>)}</div>)}</aside>
      <div className="canvas-column"><MonolithCanvas state={state} dispatch={dispatch} onSelect={setSelectedId} /><div className="canvas-legend"><span><i className="legend-module" /> Módulo</span><span><i className="legend-component" /> Componente</span><span>→ Dependencia: consumidor hacia proveedor</span><small>Arrastrá los nodos para ordenar; conectá sus puntos para crear dependencias.</small></div></div>
      <aside className="game-side-panel details-panel">{selected ? <><header><span>02 · INSPECTOR</span><h2>{String(selected.data.name)}</h2><p>{String(selected.data.description)}</p></header><div className="detail-field"><span>TIPO</span><strong>{String(selected.data.kind)}</strong></div><div className="detail-field"><span>MÓDULO</span><strong>{String(selected.data.moduleName)}</strong></div><div className="detail-field"><span>CHANGE IMPACT</span><strong>{impact} componentes</strong><small>Al cambiar este módulo, podrían necesitar cambios {impact} componentes consumidores.</small></div><h3>Dependencias</h3>{state.edges.filter((edge) => edge.source === selected.id || edge.target === selected.id).map((edge) => <p className="dependency-detail" key={edge.id}>{edge.source === selected.id ? '→' : '←'} {String(state.nodes.find((node) => node.id === (edge.source === selected.id ? edge.target : edge.source))?.data.name)}<small>{edge.data?.reason}</small></p>)}{!state.edges.some((edge) => edge.source === selected.id || edge.target === selected.id) && <p className="empty-hint">Sin dependencias todavía.</p>}<div className="learning-note"><strong>Idea para recordar</strong><p>Una dependencia puede ser razonable. Lo importante es que tenga un motivo claro y no cree una red difícil de cambiar.</p></div></> : <><header><span>02 · INSPECTOR</span><h2>Arquitectura</h2><p>Seleccioná un componente para ver su impacto y sus conexiones.</p></header><div className="metric-explainer"><strong>Cohesión · {metrics.cohesion}%</strong><p>Un módulo cohesivo mantiene juntas responsabilidades relacionadas.</p></div><div className="metric-explainer"><strong>Impacto de cambio · {metrics.changeImpact}</strong><p>Promedio de componentes que pueden verse afectados al cambiar cada módulo.</p></div>{warnings.map((warning) => <article className={`architecture-warning ${warning.severity}`} key={warning.id}><strong>{warning.severity === 'danger' ? '🔴' : '⚠'} {warning.title}</strong><p>{warning.message}</p></article>)}</>}</aside></div>
      <div className="lower-panels"><section className="ticket-panel"><div className="panel-kicker">03 · CURRENT TICKET · {Math.min(state.completedTickets.length + 1, tickets.length)} / {tickets.length}</div><div className="ticket-progress"><i style={{ width: `${completion}%` }} /></div><h2>{state.completedTickets.length >= tickets.length ? '¡Tickets completados!' : ticket.title}</h2><p>{state.completedTickets.length >= tickets.length ? 'Tu monolito ya puede evolucionar. Explorá los eventos y desafíos de arquitectura.' : ticket.description}</p>{state.completedTickets.length < tickets.length && <><h3>Componentes requeridos</h3><div className="ticket-requirements">{ticket.requiredComponents.map((id) => <button key={id} type="button" className={state.nodes.some((node) => node.id === id) ? 'done' : ''} onClick={() => addTicketComponent(id)}>{state.nodes.some((node) => node.id === id) ? '✓' : '○'} {componentCatalog.find((item) => item.id === id)?.name}<span>{state.nodes.some((node) => node.id === id) ? 'listo' : '+ Agregar'}</span></button>)}</div>{ticket.requiredDependencies?.map(([source, target]) => <p className="required-edge" key={source}>{componentCatalog.find((item) => item.id === source)?.name} → {componentCatalog.find((item) => item.id === target)?.name} <small>Conectá los nodos para cumplir este requisito.</small></p>)}<button className="game-primary-button" onClick={validate}>Validar solución</button></>}</section>
        <section className="event-panel"><div className="panel-kicker">04 · EVENTOS DE CAMBIO</div><h2>¿Qué pasa si cambia el proveedor?</h2><p>Aplicá un cambio y observá cuántos componentes están aguas arriba de Payments.</p><button className="game-small-button" onClick={handleChangeEvent} disabled={state.completedTickets.length < 3}>↻ Simular cambio</button>{state.completedTickets.length < 3 && <p className="unlock-hint">Completá tres tickets para desbloquear los cambios de negocio.</p>}<div className="advanced-row"><div><h3>Atajo arquitectónico</h3><p>Agregá toda la lógica a CommonService para salir del paso.</p></div><button className="game-small-button" onClick={handleGod} disabled={state.godModuleAccepted || state.completedTickets.length < 3}>{state.godModuleAccepted ? 'Agregado' : state.completedTickets.length < 3 ? 'Bloqueado' : 'Probar God Module'}</button></div><div className="advanced-row payment-choice"><div><h3>¿Qué hacer con Payments?</h3><p>Las tres opciones tienen costos distintos; depende del contexto.</p></div><div className="choice-buttons">{(['monolith', 'module', 'microservice'] as const).map((choice) => <button key={choice} disabled={state.completedTickets.length < 5} className={state.paymentChoice === choice ? 'chosen' : ''} onClick={() => dispatch({ type: 'payment-choice', choice })}>{choice === 'monolith' ? 'Monolito' : choice === 'module' ? 'Módulo' : 'Microservicio'}</button>)}</div></div>{state.paymentChoice && <div className="choice-result"><strong>{state.paymentChoice === 'monolith' ? '1 deployment · baja complejidad operativa' : state.paymentChoice === 'module' ? '1 deployment · límites internos más claros · costo de modularización' : '2 deployments · complejidad operativa alta · comunicación por red'}</strong></div>}</section></div>
      <section className="learning-footer"><h2>Una sola aplicación. Módulos internos separados.</h2><p>Modularizar un monolito no obliga a crear microservicios. Cada frontera explícita ayuda a que el sistema evolucione con menos impacto.</p><div className="level-strip"><span>NIVEL {state.currentLevel} · {state.currentLevel === 1 ? 'BASIC MONOLITH' : 'MODULAR MONOLITH'}</span>{state.completedTickets.length >= 2 && <span className="deployment-note">Deployment: 1 · Operational complexity: low</span>}<label>Dificultad <select value={state.difficulty} onChange={(event) => dispatch({ type: 'difficulty', difficulty: event.target.value as GameState['difficulty'] })}>{difficultyOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label></div><div className="difficulty-description">{difficultyOptions.find((option) => option.id === state.difficulty)?.description}</div></section>
    </section>{toast && <div className="game-toast" role="status"><p>{toast}</p><button onClick={() => setToast('')} aria-label="Cerrar">×</button></div>}
  </main></>;
}
export default function MonolithGame() { return <ReactFlowProvider><MonolithGameContent /></ReactFlowProvider>; }
