import type { Company } from "./types";

export const companies: Company[] = [
  {
    id: "globant",
    company: "Globant",
    role: "Semi Senior Java Developer",
    from: "2019",
    to: "2022",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Globant_Logo.svg",
    website: "https://www.globant.com",
    primaryColor: "#8BC34A",
    secondaryColor: "#F2FBEA",
    projects: [
      {
        id: "globant-banking-platform",
        name: "Banking Platform",
        subtitle: "Core Banking",
        period: "2019",
        description: "Participé del desarrollo del core bancario utilizando arquitectura basada en microservicios.",
        achievements: [
          "Migración de aplicaciones monolíticas",
          "Implementación de Kafka",
          "Mejora del rendimiento en un 40%",
        ],
        technologies: ["Java", "Spring Boot", "Kafka", "Docker", "PostgreSQL"],
        github: "https://github.com",
        demo: "https://google.com",
      },
      {
        id: "globant-bff",
        name: "BFF",
        subtitle: "Backend For Frontend",
        period: "2021",
        description: "Construcción de un Backend for Frontend para aplicaciones React.",
        achievements: ["Reducción de llamadas REST", "Cache con Redis"],
        technologies: ["Spring Boot", "Redis", "React"],
      },
    ],
  },
  {
    id: "meli",
    company: "Mercado Libre",
    role: "Senior Software Engineer",
    from: "2022",
    to: "Actualidad",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d4/MercadoLibre_logo.PNG",
    website: "https://www.mercadolibre.com",
    primaryColor: "#FFE600",
    secondaryColor: "#FFF9C4",
    projects: [
      {
        id: "meli-checkout",
        name: "Checkout LATAM",
        subtitle: "Payments",
        period: "2022",
        description: "Desarrollo del nuevo checkout para toda Latinoamérica.",
        achievements: ["Más de 10 millones de usuarios", "Alta disponibilidad", "Escalabilidad horizontal"],
        technologies: ["Java", "Spring Boot", "Kafka", "Kubernetes", "MongoDB", "Redis"],
      },
      {
        id: "meli-seller-center",
        name: "Seller Center",
        subtitle: "Marketplace",
        period: "2023",
        description: "Desarrollo de herramientas para vendedores.",
        achievements: ["Nuevo dashboard", "Mejoras de performance", "Optimización SQL"],
        technologies: ["Java", "React", "Oracle", "Redis"],
      },
      {
        id: "meli-recommendations",
        name: "Recommendations",
        subtitle: "Machine Learning",
        period: "2024",
        description: "Integración con motores de recomendación.",
        achievements: ["Integración con ML", "Disminución del tiempo de respuesta"],
        technologies: ["Spring", "Kafka", "ElasticSearch", "React"],
      },
    ],
  },
];
