import type { Company } from "./types";

export const companies: Company[] = [
  {
    id: "teamcubation",
    company: "Teamcubation",
    role: "Squad Senior · GoLang / Java · Technical Mentor",
    from: "Diciembre 2022",
    to: "Actualidad",
    location: "Buenos Aires, Argentina",
    logo: "",
    primaryColor: "#7c6dfa",
    secondaryColor: "#252044",
    summary: "Liderazgo técnico y desarrollo full stack dentro de un programa de formación de talento, combinando mentoring, arquitectura y entrega de productos internos.",
    highlights: [
      "36+ desarrolladores acompañados durante 6 waves.",
      "Learning paths para GoLang, Java, TypeScript y React.",
      "Lanzamiento de BoostersAI con Power Automate, Copilot Studio y N8N.",
    ],
    projects: [
      {
        id: "teamcubation-mentoring",
        name: "Talent Development Program",
        subtitle: "Mentoring, technical leadership y delivery real",
        period: "2022 - Actualidad",
        description: "Programa de formación y crecimiento técnico para nuevos desarrolladores, con coaching, code reviews, guía arquitectónica, feedback continuo y participación en proyectos reales.",
        achievements: ["6 waves y 36+ personas mentoreadas", "Evolución de perfiles entry-level hacia responsabilidades Semi-Senior", "Coordinación técnica durante la entrega de productos"],
        technologies: ["GoLang", "Java", "Spring Boot", "React", "TypeScript", "Node.js", "Docker"],
      },
      {
        id: "teamcubation-automation",
        name: "Internal Platforms & BoostersAI",
        subtitle: "Automatización y AI para procesos internos",
        period: "2022 - Actualidad",
        description: "Supervisión y contribución en herramientas de QA, onboarding, generación de usuarios y perfiles, sincronización multi-base, cálculo de riesgo y capacitación en automatización para perfiles no técnicos.",
        achievements: ["Orquestación de servicios e integraciones con Google Chat", "Aplicación de riesgo con GoLang y React/TypeScript", "Múltiples ciclos de capacitación en low-code y AI"],
        technologies: ["GoLang", "React", "TypeScript", "Vite", "MongoDB", "RabbitMQ", "OKTA", "Power Automate", "N8N"],
      },
    ],
  },
  {
    id: "globant-cabify",
    company: "Globant",
    client: "Cabify · COPs · Driver Acquisition",
    role: "Full Stack GoLang / Java Developer SSR",
    from: "Abril 2021",
    to: "Noviembre 2022",
    location: "Provincia de Buenos Aires, Argentina",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Globant_Logo.svg",
    website: "https://www.globant.com",
    primaryColor: "#8BC34A",
    secondaryColor: "#26351d",
    summary: "Desarrollo de sistemas para adquisición de conductores y middleware de datos dentro del ecosistema de Cabify.",
    highlights: [
      "Construcción del sistema Harvey para procesar solicitudes y crear tickets en Zendesk.",
      "Middlewares con gRPC, mensajería y sincronización de datos con el CORE.",
      "Mantenimiento, soporte técnico y asesoramiento sobre aplicaciones de negocio.",
    ],
    projects: [
      {
        id: "globant-harvey",
        name: "Harvey",
        subtitle: "Harassment request processing",
        period: "2021 - 2022",
        description: "Sistema para recibir y procesar solicitudes de harassment, resolverlas y crear tickets en Zendesk con el resultado del proceso.",
        achievements: ["Maintainer Website frontend y backend", "Harvey Process Server", "Zendesk form integrado al flujo"],
        technologies: ["GoLang", "Java", "Node.js", "Zendesk", "Docker", "Google Cloud Run"],
      },
      {
        id: "globant-middlewares",
        name: "COPs, Reservas & Chismoso Middleware",
        subtitle: "Centralización, filtrado y enriquecimiento de mensajes",
        period: "2021 - 2022",
        description: "Conjunto de servicios para centralizar datos del área de COPs, filtrar mensajes de Reservas, completar información desde otras aplicaciones y publicar eventos mediante APIs y sistemas de mensajería.",
        achievements: ["Intermediación entre aplicaciones heterogéneas y el CORE", "Sincronización basada en eventos", "Integraciones con Kibana, Elastic, Rollbar y Amplitude"],
        technologies: ["GoLang", "gRPC", "Messaging", "Groovy", "Java", "Docker", "GitLab", "Google Cloud Run"],
      },
    ],
  },
  {
    id: "baufest-bbva",
    company: "Baufest",
    client: "BBVA",
    role: "Full Stack Java Developer SSR",
    from: "Febrero 2020",
    to: "Abril 2021",
    location: "Buenos Aires, Argentina",
    logo: "",
    primaryColor: "#4f8cff",
    secondaryColor: "#182847",
    summary: "Desarrollo full stack para BBVA, combinando Java legacy y moderno con Spring, Go, Kotlin y tecnologías frontend.",
    highlights: [
      "Trabajo con Java 1.6/1.8, Spring, Spring Boot, Go y Kotlin.",
      "Experiencia con MS-SQL, PostgreSQL, JavaScript, HTML y CSS.",
      "Baufest Ambassador, Gaming Interest Group Leader y mentor en onboardings.",
    ],
    projects: [
      {
        id: "baufest-bbva-fullstack",
        name: "BBVA Full Stack Development",
        subtitle: "Enterprise banking systems",
        period: "2020 - 2021",
        description: "Desarrollo y mantenimiento de soluciones full stack para BBVA, trabajando sobre aplicaciones empresariales y distintos niveles del stack.",
        achievements: ["Evolución de aplicaciones Java legacy", "Desarrollo con Spring y Spring Boot", "Participación en capacitación y onboarding"],
        technologies: ["Java 1.6/1.8", "Spring", "Spring Boot", "Go", "Kotlin", "JavaScript", "MS-SQL", "PostgreSQL", "Maven"],
      },
    ],
  },
  {
    id: "adamat",
    company: "ADAMAT S.A.",
    role: "Systems Administration Manager",
    from: "Abril 2017",
    to: "Febrero 2020",
    location: "Capital Federal, Argentina",
    logo: "",
    primaryColor: "#fa6d6d",
    secondaryColor: "#3a2028",
    summary: "Gestión integral del área de Sistemas y Administración, con responsabilidad sobre objetivos, estructura, personas, operaciones y decisiones de negocio.",
    highlights: [
      "Planificación de objetivos generales y específicos de corto y largo plazo.",
      "Dirección, supervisión y liderazgo del área de Sistemas y Administración.",
      "Participación en selección, capacitación y estructura organizacional.",
    ],
    projects: [
      {
        id: "adamat-management",
        name: "Systems & Administration Management",
        subtitle: "Operations, people y business coordination",
        period: "2017 - 2020",
        description: "Responsabilidad sobre la planificación, organización y control del área de Sistemas y Administración, coordinando necesidades operativas, estructura, compras, personal y soporte a la dirección.",
        achievements: ["Definición de objetivos y estructura organizacional", "Liderazgo del equipo y supervisión de actividades", "Asesoramiento en contratación, capacitación y decisiones administrativas"],
        technologies: ["Systems Management", "Team Leadership", "Strategic Planning", "Operations"],
      },
    ],
  },
  {
    id: "coca-cola-latam",
    company: "The Coca-Cola Company",
    client: "Process Technologies · LATAM",
    role: "Business Intelligence Project Lead",
    from: "Diciembre 2006",
    to: "Abril 2017",
    location: "Argentina · South Latin · Latin Center",
    logo: "",
    primaryColor: "#e86b82",
    secondaryColor: "#3a222c",
    summary: "Más de diez años liderando iniciativas de BI, migraciones de datos, herramientas de análisis y soporte regional para distintos países de Latinoamérica.",
    highlights: [
      "Migraciones y unificación de MSSQL 2000, MSSQL 2005 y DB Global.",
      "Creación y crecimiento del área de BI Support para South Latin y Latin Center.",
      "Implementación de QlikView, Master Data, Pricing y Value Chain Analysis.",
      "Crecimiento del equipo bajo responsabilidad de 1 a 4 personas.",
    ],
    projects: [
      {
        id: "coca-cola-data",
        name: "Data Centralization & Migration",
        subtitle: "Regional data foundations",
        period: "2007 - 2014",
        description: "Centralización, migración y unificación de bases de Argentina, Perú y Chile, y evolución posterior hacia una base global para South Latin y Latin Center.",
        achievements: ["Centralización de MSSQL 2000", "Migración hacia MSSQL 2005 y DB Global", "Unificación de información regional y estabilización de procesos"],
        technologies: ["MSSQL 2000", "MSSQL 2005", "DB Global", "Data Migration", "Master Data"],
      },
      {
        id: "coca-cola-bi",
        name: "BI Support & Value Chain Analysis",
        subtitle: "Support, analytics y team growth",
        period: "2008 - 2017",
        description: "Creación y liderazgo del área de soporte de BI para South Latin y Latin Center, acompañando aplicaciones, QlikView, pricing, costos, descuentos y Value Chain Analysis.",
        achievements: ["Expansión de cobertura regional", "Crecimiento del equipo de 1 a 4 personas", "Implementación y estabilización de herramientas de BI para LATAM"],
        technologies: ["QlikView", "BI", "SQL Server", "Pricing", "Value Chain Analysis", "Team Leadership"],
      },
    ],
  },
];
